import test from 'node:test';
import assert from 'node:assert/strict';
import {Game,validTie} from '../game.js';
import {CONFIG,HERBS} from '../config.js';
const line=[{x:.1,y:.3},{x:.5,y:.3},{x:.9,y:.3}];
function setup(){let now=0;const g=new Game(()=>now);return {g,advance(ms){now+=ms;g.tick();}};}
function weigh(g,herbs=['rose']){for(const h of herbs){assert.ok(g.pickup(h));assert.ok(g.weigh(h));}}
function processed(ctx,herbs=['rose'],method='grind'){weigh(ctx.g,herbs);ctx.advance(1000);assert.ok(ctx.g.process(method));if(method==='grind'){ctx.advance(5000);assert.ok(ctx.g.grindClick());}else for(let i=0;i<5;i++){ctx.advance(600);assert.ok(ctx.g.steamClick(ctx.g.steamTarget()));}}
function bag(ctx,herbs=['rose'],style='red',slot=0){processed(ctx,herbs);assert.ok(ctx.g.store(slot,'grind'));assert.ok(ctx.g.placeBag(slot,style));assert.ok(ctx.g.fill(slot,slot));assert.ok(ctx.g.openPack(slot));assert.ok(ctx.g.tie(line));}
test('three minutes map 08:00 to 18:00 and next day preserves silver',()=>{const {g,advance}=setup();assert.equal(g.clock(),'08:00');advance(90000);assert.equal(g.clock(),'13:00');advance(90000);assert.equal(g.clock(),'18:00');assert.ok(g.s.closed);g.s.silver=24;assert.ok(g.nextDay());assert.equal(g.s.day,2);assert.equal(g.s.silver,24);assert.equal(g.clock(),'08:00');});
test('customers arrive one by one and have separate moods and patience',()=>{const {g,advance}=setup();assert.equal(g.s.customers.filter(Boolean).length,1);advance(18000);assert.equal(g.s.customers.filter(Boolean).length,2);advance(9000);assert.equal(g.mood(g.s.customers[0]),'worried');assert.equal(g.mood(g.s.customers[1]),'calm');advance(25000);assert.equal(g.mood(g.s.customers[0]),'angry');advance(13000);assert.equal(g.s.customers[0].state,'left');});
test('orders support one through four ingredients and both bag styles',()=>{const {g}=setup();const counts=[g.s.customers[0].ingredients.length];for(let i=0;i<3;i++){g.arrive(0);counts.push(g.s.customers[0].ingredients.length);}assert.deepEqual(counts,[1,2,3,4]);assert.equal(g.s.customers[0].style,'blue');});
test('five pickups empty stock; cancel refunds; exactly five clicks replenish',()=>{const {g}=setup();g.pickup('rose');g.refund('rose');assert.equal(g.s.stock.rose,5);for(let i=0;i<5;i++)assert.ok(g.pickup('rose'));assert.equal(g.s.stock.rose,0);assert.equal(g.pickup('rose'),false);for(let i=0;i<4;i++)g.restock('rose');assert.equal(g.s.stock.rose,0);g.restock('rose');assert.equal(g.s.stock.rose,5);assert.equal(g.restock('lavender'),false);});
test('multiple ingredients weigh together and transfer atomically',()=>{const ctx=setup(),{g}=ctx;weigh(g,HERBS);assert.equal(g.weigh('rose'),false);assert.equal(g.process('grind'),false);ctx.advance(1000);assert.ok(g.process('grind'));assert.equal(g.s.scale,null);assert.deepEqual(g.s.tools.grind.ingredients,HERBS);});
test('automatic grind is not ready before click, green starts at five seconds',()=>{const ctx=setup(),{g}=ctx;weigh(g);ctx.advance(1000);g.process('grind');ctx.advance(4999);assert.equal(g.grindClick(),false);ctx.advance(1);assert.ok(g.grindGreen());assert.equal(g.s.tools.grind.stage,'processing');assert.ok(g.grindClick());assert.equal(g.s.tools.grind.quantity,2);});
test('missed grinding window repeats without losing material',()=>{const ctx=setup(),{g}=ctx;weigh(g);ctx.advance(1000);g.process('grind');ctx.advance(6700);assert.equal(g.grindClick(),false);ctx.advance(6000);assert.ok(g.grindClick());});
test('steaming needs green hits, no automatic completion',()=>{const ctx=setup(),{g}=ctx;weigh(g);ctx.advance(1000);g.process('steam');ctx.advance(10000);assert.equal(g.s.tools.steam.progress,0);const wrong=g.steamTarget()>.5?0:1;assert.equal(g.steamClick(wrong),false);for(let i=0;i<5;i++){ctx.advance(600);g.steamClick(g.steamTarget());}assert.equal(g.s.tools.steam.stage,'ready');assert.equal(g.s.tools.steam.quantity,2);});
test('stations operate independently; occupied station preserves scale',()=>{const ctx=setup(),{g}=ctx;weigh(g);ctx.advance(1000);g.process('grind');weigh(g,['clove']);ctx.advance(1000);assert.equal(g.process('grind'),false);assert.deepEqual(g.s.scale.ingredients,['clove']);assert.ok(g.process('steam'));assert.ok(g.s.tools.grind);assert.ok(g.s.tools.steam);});
test('two portions share one plate, with an empty bag on the same plate',()=>{const ctx=setup(),{g}=ctx;processed(ctx,['rose','clove']);g.placeBag(0,'blue');assert.ok(g.store(0,'grind'));assert.equal(g.s.slots[0].material.quantity,2);assert.ok(g.fill(0,0));assert.equal(g.s.slots[0].material.quantity,1);assert.deepEqual(g.s.slots[0].bag.ingredients,['rose','clove']);assert.equal(g.fill(0,0),false);assert.equal(g.s.slots[0].material.quantity,1);});
test('invalid tying preserves bag, valid line seals without using second portion',()=>{const ctx=setup(),{g}=ctx;processed(ctx);g.store(0,'grind');g.placeBag(0,'red');assert.equal(g.openPack(0),false);g.fill(0,0);g.openPack(0);assert.equal(g.tie([{x:.1,y:.9},{x:.9,y:.9}]),false);assert.ok(g.tie(line));assert.ok(g.s.slots[0].bag.sealed);assert.equal(g.s.slots[0].material.quantity,1);assert.equal(validTie([]),false);});
test('correct delivery earns normal income once',()=>{const ctx=setup(),{g}=ctx;bag(ctx);assert.deepEqual(g.deliver(0,0),{correct:true,amount:24});assert.equal(g.s.silver,24);assert.equal(g.s.dayIncome,24);assert.equal(g.deliver(0,0),false);assert.equal(g.s.silver,24);});
test('wrong ingredient or bag style is accepted with low pay and angry customer',()=>{for(const [herbs,style] of [[['clove'],'red'],[['rose'],'blue']]){const ctx=setup(),{g}=ctx;bag(ctx,herbs,style);assert.deepEqual(g.deliver(0,0),{correct:false,amount:2});assert.equal(g.s.slots[0].bag,null);assert.equal(g.s.customers[0].state,'disappointed');}});
test('waste can remove scale, processing tool, plate material and bag',()=>{const ctx=setup(),{g}=ctx;weigh(g);g.discard('scale');assert.equal(g.s.scale,null);weigh(g);ctx.advance(1000);g.process('steam');g.discard('tool','steam');assert.equal(g.s.tools.steam,null);processed(ctx);g.store(0,'grind');g.placeBag(0,'red');g.discard('material',0);assert.equal(g.s.slots[0].material,null);assert.ok(g.s.slots[0].bag);g.discard('bag',0);assert.equal(g.s.slots[0].bag,null);});
test('pause freezes day, patience and processing; input cannot consume resources',()=>{const ctx=setup(),{g}=ctx;weigh(g);ctx.advance(1000);g.process('grind');ctx.advance(3000);g.pause();const clock=g.clock(),p=g.patience(g.s.customers[0]);ctx.advance(60000);assert.equal(g.clock(),clock);assert.equal(g.patience(g.s.customers[0]),p);assert.equal(g.pickup('rose'),false);g.resume();assert.equal(g.grindPhase(),3000);ctx.advance(2000);assert.ok(g.grindClick());});
test('ingredient inspection reports exact mixtures at every station',()=>{const ctx=setup(),{g}=ctx;weigh(g,['rose','mint']);assert.deepEqual(g.ingredients('scale'),['rose','mint']);ctx.advance(1000);g.process('grind');assert.deepEqual(g.ingredients('tool','grind'),['rose','mint']);ctx.advance(5000);g.grindClick();g.store(0,'grind');assert.deepEqual(g.ingredients('material',0),['rose','mint']);g.placeBag(1,'blue');g.fill(0,1);assert.deepEqual(g.ingredients('bag',1),['rose','mint']);});
test('occupied tray preserves ready batch; duplicate or fifth ingredient does not consume a portion',()=>{const ctx=setup(),{g}=ctx;processed(ctx,HERBS);g.store(0,'grind');g.placeBag(1,'red');g.fill(0,1);processed(ctx,['rose']);assert.equal(g.store(0,'grind'),false);assert.equal(g.s.tools.grind.quantity,2);g.store(2,'grind');assert.equal(g.fill(2,1),false);assert.equal(g.s.slots[2].material.quantity,2);});
test('closed shop blocks input and second next-day request',()=>{const {g,advance}=setup();advance(CONFIG.dayDuration);assert.equal(g.pickup('rose'),false);assert.equal(g.placeBag(0,'red'),false);assert.equal(g.nextDay(),true);assert.equal(g.nextDay(),false);});
